Repository dotnet/docs.zh-tw, pull requests merged in 2019-10, with the labels that each got.

#239 Fix typo
  docs/csharp/language-reference/keywords/throw.md
Labels: Accepted

#241 Row and column problem
  docs/csharp/programming-guide/arrays/multidimensional-arrays.md
Labels: Accepted, Linguistic Suggestion

#244 Update deploy-with-cli.md
  docs/core/deploying/deploy-with-cli.md
Labels: Accepted

#246 Update index.md
  docs/core/porting/index.md
Labels: Accepted, Linguistic Suggestion

#245 Update deploy-with-vs.md
  docs/core/deploying/deploy-with-vs.md
Labels: Accepted

#250 Update portability-analyzer.md
  docs/standard/analyzers/portability-analyzer.md
Labels: In Progress

#247 Update null-coalescing-operator.md
  docs/csharp/language-reference/operators/null-coalescing-operator.md
Labels: Accepted, Linguistic Suggestion

#248 Update null-forgiving.md
  docs/csharp/language-reference/operators/null-forgiving.md
Labels: Accepted, Linguistic Suggestion

#249 Update index.md
  docs/core/porting/index.md
Labels: Accepted, Linguistic Suggestion
